project:
  type: book

book:
  title: "dav-sterbetafeln"
  author: "Norah Jones"
  date: "9.11.2025"
  chapters:
    - index.qmd
    - part: DAV 1994 T
      chapters: 
      - dav94t-uebersicht.qmd
    - part: dav2008t/dav2008t.qmd
      chapters: 
      - dav2008t/xxx.qmd
      - dav2008t/quellen.qmd

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

